# Generated by Django 5.2.6 on 2025-09-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
